// <auto-generated />
using System;
using Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(CanilAppDbContext))]
    [Migration("20251001174910_VersaoInicial")]
    partial class VersaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Backend.Models.Medicamentos.MedicamentosModel", b =>
                {
                    b.Property<int>("CodigoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumoAnual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumoMensal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDeEntradaDoMedicamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoMedicamentos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntradaEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstoqueDisponivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeComercial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotaFiscal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicoAlvo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaidaTotalEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ValidadeMedicamento")
                        .HasColumnType("TEXT");

                    b.HasKey("CodigoId");

                    b.ToTable("Medicamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
