// <auto-generated />
using System;
using Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(CanilAppDbContext))]
    [Migration("20251104004423_MigrationDeCorrecaoComEstoque")]
    partial class MigrationDeCorrecaoComEstoque
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Backend.Models.ItemComEstoqueBaseModel", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("IdItem");

                    b.ToTable("ItensBase", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Backend.Models.ItemEstoqueModel", b =>
                {
                    b.Property<int>("IdItem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lote")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraInsercaoRegistro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("NFe")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdItem", "Lote");

                    b.ToTable("ItensEstoque");
                });

            modelBuilder.Entity("Backend.Models.ItemNivelEstoqueModel", b =>
                {
                    b.Property<int>("IdItem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraInsercaoRegistro")
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelMinimoEstoque")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdItem");

                    b.ToTable("ItensNivelEstoque");
                });

            modelBuilder.Entity("Backend.Models.Medicamentos.InsumosModel", b =>
                {
                    b.Property<int>("CodigoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumoAnual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumoMensal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDeEntradaDoMedicamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoDetalhada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoSimplificada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntradaEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstoqueDisponivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotaFiscal")
                        .HasColumnType("TEXT");

                    b.Property<int>("SaidaTotalEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unidade")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ValidadeInsumo")
                        .HasColumnType("TEXT");

                    b.HasKey("CodigoId");

                    b.ToTable("Insumos", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Medicamentos.MedicamentosModel", b =>
                {
                    b.Property<int>("CodigoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumoAnual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumoMensal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDeEntradaDoMedicamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoMedicamentos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntradaEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstoqueDisponivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeComercial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotaFiscal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicoAlvo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaidaTotalEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ValidadeMedicamento")
                        .HasColumnType("TEXT");

                    b.HasKey("CodigoId");

                    b.ToTable("Medicamentos", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Usuarios.UsuariosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraExpiracaoRefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashSenha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Permissao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimeiroNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Backend.Models.Produtos.ProdutosModel", b =>
                {
                    b.HasBaseType("Backend.Models.ItemComEstoqueBaseModel");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraInsercaoRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoDetalhada")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoSimples")
                        .HasColumnType("TEXT");

                    b.Property<int>("Unidade")
                        .HasColumnType("INTEGER");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ItemEstoqueModel", b =>
                {
                    b.HasOne("Backend.Models.ItemComEstoqueBaseModel", "ItemBase")
                        .WithMany("ItensEstoque")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemBase");
                });

            modelBuilder.Entity("Backend.Models.ItemNivelEstoqueModel", b =>
                {
                    b.HasOne("Backend.Models.ItemComEstoqueBaseModel", "ItemBase")
                        .WithOne("ItemNivelEstoque")
                        .HasForeignKey("Backend.Models.ItemNivelEstoqueModel", "IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemBase");
                });

            modelBuilder.Entity("Backend.Models.Produtos.ProdutosModel", b =>
                {
                    b.HasOne("Backend.Models.ItemComEstoqueBaseModel", null)
                        .WithOne()
                        .HasForeignKey("Backend.Models.Produtos.ProdutosModel", "IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.ItemComEstoqueBaseModel", b =>
                {
                    b.Navigation("ItemNivelEstoque")
                        .IsRequired();

                    b.Navigation("ItensEstoque");
                });
#pragma warning restore 612, 618
        }
    }
}
