// <auto-generated />
using System;
using Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(CanilAppDbContext))]
    partial class CanilAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Backend.Models.Medicamentos.MedicamentosModel", b =>
                {
                    b.Property<string>("CodigoId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ConsumoAnual")
                        .HasColumnType("int");

                    b.Property<int>("ConsumoMensal")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoMedicamentos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EntradaEstoque")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueDisponivel")
                        .HasColumnType("int");

                    b.Property<string>("HorV")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeComercial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NotaFiscal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<int>("SaidaTotalEstoque")
                        .HasColumnType("int");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CodigoId");

                    b.ToTable("Medicamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
